### ISSUE TITLE
Erc20 standard method is missing （BalanceOf...）

### ISSUE THREAD

**Issue by WoeOm** [evolutionlandorg/evo-deploy#2]
https://github.com/evolutionlandorg/evo-deploy/blob/5a163a3f892fc558397c38af16308ec486b4f185/src/wrapper/WCRING.sol#L22

https://eips.ethereum.org/EIPS/eip-20

**Comment by hujw77** [comment]
https://github.com/evolutionlandorg/evo-deploy/blob/5a163a3f892fc558397c38af16308ec486b4f185/src/wrapper/WCRING.sol#L32

This could generate the abi `balanceOf`.
`allowance ` is the same way.
